Revert "Bump maven-enforcer-plugin from 3.0.0-M3 to 3.0.0 (#250)"
This reverts commit 09cc1d54a58e753921509d1be6bf85f9f840cd93.

Enforcer fails with:
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project maven-site: failed to get report for org.apache.maven.plugins:maven-surefire-report-plugin: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-bytecode-version) on project maven-site: Unable to parse configuration of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce for parameter enforceBytecodeVersion: Cannot create instance of class org.apache.maven.plugins.enforcer.EnforceBytecodeVersion: org/apache/maven/shared/dependency/tree/DependencyTreeBuilderException: org.apache.maven.shared.dependency.tree.DependencyTreeBuilderException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project maven-site: failed to get report for org.apache.maven.plugins:maven-surefire-report-plugin