Attempting to simplify the modification I made to the download page so it won't trigger a NoSuchMethodError in the PDF plugin, and adding releases for maven-filtering and maven-resources-plugin.
git-svn-id: https://svn.apache.org/repos/asf/maven/site/trunk@807816 13f79535-47bb-0310-9956-ffa450edef68